### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bcddfggghkstg** [masterjanic/discord-checker-web#8]
- Bot Token Information
- Token Joiner
- Prevent Rate Limits??
- half my tokens are able to be put in, issue with regenx?

**Comment by masterjanic** [comment]
Hey, thanks for your suggestions.

When I am testing the tool I have no problem with rate limits, maybe you have disabled your cache in the Developer Tools? Discord allows about ~60 requests per seconds to the api without rate limit which is not even the speed of the checker. I will have a look into further improvements.

For the tokens, can you provide a sample so that I can check why it does not get detected? You can also message me privately on Discord if you like: @masterjanic

**Comment by bcddfggghkstg** [comment]
the tokens issue are when u copy 2 different tokens at once and their in 1 line.

**Comment by masterjanic** [comment]
> the tokens issue are when u copy 2 different tokens at once and their in 1 line.

Yes, thats not possible unfortunately since there are different token formats of different lengths. So you must input your tokens separated by a new line or at least a space between otherwise there is no way to differentiate them.

**Comment by bcddfggghkstg** [comment]
there's already a newline

**Comment by masterjanic** [comment]
I can't reproduce this error. Can you provide a sample or contact me on Discord so that I can resolve this issue, please?
